import Head from "next/head";
import Navbar from "../molecules/Navbar/navbar";
import style from "./layout/layout.module.css";

const Layout = ({ ...props }) => {
  return (
    <div className={style.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{props.children}</main>
    </div>
  );
};

export default Layout;
